name = "maximost-frontend"
compatibility_date = "2024-07-02"
pages_build_output_dir = "dist"

# These variables are available to both the build process and the backend worker at runtime.
[vars]
# --- Frontend Variables (for React code) ---
# These MUST be prefixed with VITE_ to be exposed to the client-side code.
VITE_FIREBASE_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"
VITE_FIREBASE_AUTH_DOMAIN = "maximost-a0401.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "maximost-a0401"
VITE_FIREBASE_STORAGE_BUCKET = "maximost-a0401.appspot.com"
VITE_FIREBASE_MESSAGING_SENDER_ID = "161512806223"
VITE_FIREBASE_APP_ID = "1:161512806223:web:5bde0190d46718f8a5973a"

# --- Backend Variables (for Hono API code) ---
# These have NO prefix and are only available to the backend worker.
FIREBASE_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"
FIREBASE_PROJECT_ID = "maximost-a0401"
# RENAMED to avoid deployment conflict. This key is for the AUTH middleware.
FIREBASE_AUTH_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"

# It's good practice to mirror the variables for your preview deployments.
[env.preview.vars]
# --- Frontend Preview Variables ---
VITE_FIREBASE_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"
VITE_FIREBASE_AUTH_DOMAIN = "maximost-a0401.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "maximost-a0401"
VITE_FIREBASE_STORAGE_BUCKET = "maximost-a0401.appspot.com"
VITE_FIREBASE_MESSAGING_SENDER_ID = "161512806223"
VITE_FIREBASE_APP_ID = "1:161512806223:web:5bde0190d46718f8a5973a"

# --- Backend Preview Variables ---
FIREBASE_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"
FIREBASE_PROJECT_ID = "maximost-a0401"
# RENAMED to avoid deployment conflict. This key is for the AUTH middleware.
FIREBASE_AUTH_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"