# This is the single source of truth for your Cloudflare Pages deployment.
# It configures both the frontend build and the backend worker's environment.

name = "maximost-frontend"
compatibility_date = "2024-07-02"
pages_build_output_dir = "dist"

# These variables are for the PRODUCTION environment (main branch)
[vars]
# --- Frontend Variables (for React code) ---
VITE_FIREBASE_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"
VITE_FIREBASE_AUTH_DOMAIN = "maximost-a0401.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "maximost-a0401"
VITE_FIREBASE_STORAGE_BUCKET = "maximost-a0401.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "161512806223"
VITE_FIREBASE_APP_ID = "1:161512806223:web:5bde0190d46718f8a5973a"

# --- Backend Variables (for Hono API code) ---
# These are required for the backend to function correctly.
FIREBASE_API_KEY = "YOUR_NEW_SERVER_API_KEY_HERE" # Replace with the new key you generated
FIREBASE_PROJECT_ID = "maximost-a0401"
FIREBASE_AUTH_API_KEY = "YOUR_NEW_SERVER_API_KEY_HERE" # Replace with the new key you generated

# These variables are for ALL PREVIEW environments (feature branches)
[env.preview.vars]
# --- Frontend Preview Variables ---
VITE_FIREBASE_API_KEY = "AIzaSyAml6FYQQOuhG2_EpPRs2AahkdDWdeic5w"
VITE_FIREBASE_AUTH_DOMAIN = "maximost-a0401.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "maximost-a0401"
VITE_FIREBASE_STORAGE_BUCKET = "maximost-a0401.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "161512806223"
VITE_FIREBASE_APP_ID = "1:161512806223:web:5bde0190d46718f8a5973a"

# --- Backend Preview Variables ---
FIREBASE_API_KEY = "AIzaSyAYZn2l833Vv2tJ4C0eDtQ2WdilRgQ3Qcg"
FIREBASE_PROJECT_ID = "maximost-a0401"
FIREBASE_AUTH_API_KEY = "AIzaSyAYZn2l833Vv2tJ4C0eDtQ2WdilRgQ3Qcg"
