name = "maximost-backend"
main = "src/worker.ts"
compatibility_date = "2024-06-11"

# This section tells wrangler how to build the project
[build]
command = "npm run build"

# This line is now at the correct top-level and enables Node.js compatibility
compatibility_flags = [ "nodejs_compat" ]