name = "maximost-backend"
main = "src/worker.ts"
compatibility_date = "2024-06-12"

# This is the correct flag with the correct syntax for Wrangler v4
compatibility_flags = [ "nodejs_compat" ]

# This section tells wrangler how to build the project
[build]
command = "npm run build"