name = "maximost-backend"
main = "src/worker.ts"
compatibility_date = "2024-06-11"

# This is the critical fix
[build]
command = "npm run build"

[durable_objects]
bindings = []

[migrations]
tag = "v1"
new_classes = []

[[r2_buckets]]
binding = ""
bucket_name = ""
preview_bucket_name = ""

[[services]]
binding = ""
service = ""
environment = ""

# This line enables Node.js compatibility
compatibility_flags = [ "nodejs_compat" ]