name = "maximost-backend"
main = "src/worker.ts"
compatibility_date = "2024-06-11"

# This line MUST be at the top level, not inside any brackets.
compatibility_flags = [ "nodejs_compat" ]

# This section tells wrangler how to build the project.
[build]
command = "npm run build"