name = "maximost-backend"
main = "src/worker.ts"
compatibility_date = "2024-06-12"

# This flag MUST be at the top level to enable Node.js modules.
compatibility_flags = [ "nodejs_compat" ]

# This section tells wrangler how to build the project.
[build]
command = "npm run build"