name = "maximost-backend"
main = "src/worker.ts"

# This is the key change, as suggested by the error log.
compatibility_date = "2024-09-23"

compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build"