// docs/sample-data.ts
import { FirestoreUser, FirestoreHabit } from '../shared/types/firestore';

// Helper function to create a placeholder Timestamp object for sample data
// In a real scenario, these would be actual Firestore Timestamps.
const createSampleTimestamp = (dateString: string): any => {
  // This is a simplified placeholder. Firestore Timestamps have specific methods.
  // For sample data, a string or a Date object might be sufficient,
  // but we'll try to match the interface structure.
  const date = new Date(dateString);
  return {
    toDate: () => date,
    // seconds: Math.floor(date.getTime() / 1000),
    // nanoseconds: (date.getTime() % 1000) * 1e6,
  };
};

export const sampleUsers: FirestoreUser[] = [
  {
    email: "user1@example.com",
    displayName: "Alice Stoic",
    createdAt: createSampleTimestamp("2024-01-15T10:00:00Z"),
    selectedCoach: "stoic",
    premiumStatus: "premium",
    lastLogin: createSampleTimestamp("2024-07-20T10:00:00Z"),
  },
  {
    email: "user2@example.com",
    displayName: "Bob Operator",
    createdAt: createSampleTimestamp("2024-02-20T11:30:00Z"),
    selectedCoach: "operator",
    premiumStatus: "free",
    lastLogin: createSampleTimestamp("2024-07-21T15:20:00Z"),
  },
];

export const sampleHabits: FirestoreHabit[] = [
  {
    // habitId will be auto-generated by Firestore
    userId: "user1@example.com", // In reality, this would be the Firebase UID for Alice
    title: "Morning Meditation",
    description: "15 minutes of guided meditation.",
    category: "Mental Acuity & Growth",
    createdAt: createSampleTimestamp("2024-01-16T08:00:00Z"),
    isActive: true,
    completions: [
      createSampleTimestamp("2024-07-18T08:00:00Z"),
      createSampleTimestamp("2024-07-19T08:00:00Z"),
      createSampleTimestamp("2024-07-20T08:00:00Z"),
    ],
    isBadHabit: false,
  },
  {
    userId: "user1@example.com", // Alice's UID
    title: "Limit Social Media to 30 mins",
    description: "Track time spent and stick to the limit.",
    category: "Digital Wellbeing",
    createdAt: createSampleTimestamp("2024-03-01T12:00:00Z"),
    isActive: true,
    completions: [],
    isBadHabit: true,
    trigger: "Feeling bored or anxious",
    replacementHabit: "Read a book or go for a short walk",
  },
  {
    userId: "user2@example.com", // Bob's UID
    title: "Complete Scheduled Workout",
    description: "Follow the prescribed workout plan for the day.",
    category: "Physical Training",
    createdAt: createSampleTimestamp("2024-02-22T17:00:00Z"),
    isActive: true,
    completions: [
      createSampleTimestamp("2024-07-19T18:00:00Z"),
      createSampleTimestamp("2024-07-21T17:30:00Z"),
    ],
    isBadHabit: false,
  },
  {
    userId: "user2@example.com", // Bob's UID
    title: "Review Daily Tasks Before Bed",
    description: "Plan for the next day.",
    category: "Productivity",
    createdAt: createSampleTimestamp("2024-05-10T21:00:00Z"),
    isActive: false, // Archived habit
    completions: [
      createSampleTimestamp("2024-06-01T21:00:00Z"),
      createSampleTimestamp("2024-06-02T21:00:00Z"),
    ],
    isBadHabit: false,
  },
];

// Note: For userId in sampleHabits, it's currently using email.
// In a real Firestore setup, this would be the actual Firebase Authentication UID.
// This is just for illustrative sample data.
