// docs/sample-data.ts
import { FirestoreUser, FirestoreHabit, HabitCompletionEntry, FirestoreTimestamp } from '../shared/types/firestore';

// Helper function to create a placeholder Timestamp object for sample data
const createSampleTimestamp = (dateString: string): FirestoreTimestamp => {
  const date = new Date(dateString);
  return {
    toDate: () => date,
    seconds: Math.floor(date.getTime() / 1000),
    nanoseconds: (date.getTime() % 1000) * 1e6,
  };
};

export const sampleUsers: FirestoreUser[] = [
  {
    email: "user1@example.com",
    displayName: "Alice Stoic",
    createdAt: createSampleTimestamp("2024-01-15T10:00:00Z"),
    selectedCoach: "stoic",
    premiumStatus: "premium",
    lastLogin: createSampleTimestamp("2024-07-20T10:00:00Z"),
  },
  {
    email: "user2@example.com",
    displayName: "Bob Operator",
    createdAt: createSampleTimestamp("2024-02-20T11:30:00Z"),
    selectedCoach: "operator",
    premiumStatus: "free",
    lastLogin: createSampleTimestamp("2024-07-21T15:20:00Z"),
  },
];

export const sampleHabits: FirestoreHabit[] = [
  {
    // habitId will be auto-generated by Firestore, so not included here for "creation" samples
    userId: "user1@example.com", // In reality, this would be the Firebase UID for Alice
    title: "Morning Meditation",
    description: "15 minutes of guided meditation.",
    category: "Mental Acuity & Growth",
    createdAt: createSampleTimestamp("2024-01-16T08:00:00Z"),
    isActive: true,
    type: "binary", // New field
    completions: [ // Updated structure
      { date: "2024-07-18", value: 1, timestamp: createSampleTimestamp("2024-07-18T08:05:00Z") },
      { date: "2024-07-19", value: 1, timestamp: createSampleTimestamp("2024-07-19T08:03:00Z") },
      { date: "2024-07-20", value: 1, timestamp: createSampleTimestamp("2024-07-20T08:07:00Z") },
    ],
    isBadHabit: false,
    icon: "brain",
    iconColor: "purple",
    frequency: "daily",
    isAbsolute: true,
  },
  {
    userId: "user1@example.com",
    title: "Limit Social Media to 30 mins",
    description: "Track time spent and stick to the limit.",
    category: "Digital Wellbeing",
    createdAt: createSampleTimestamp("2024-03-01T12:00:00Z"),
    isActive: true,
    type: "quantitative", // New field
    targetValue: 30,       // New field
    targetUnit: "minutes", // New field
    completions: [
      { date: "2024-07-19", value: 45, timestamp: createSampleTimestamp("2024-07-19T22:00:00Z") }, // Exceeded target
      { date: "2024-07-20", value: 25, timestamp: createSampleTimestamp("2024-07-20T21:30:00Z") }, // Met target
    ],
    isBadHabit: true,
    trigger: "Feeling bored or anxious",
    replacementHabit: "Read a book or go for a short walk",
    icon: "smartphone",
    iconColor: "red",
    frequency: "daily",
    isAbsolute: true,
  },
  {
    userId: "user2@example.com",
    title: "Complete Scheduled Workout",
    description: "Follow the prescribed workout plan for the day.",
    category: "Physical Training",
    createdAt: createSampleTimestamp("2024-02-22T17:00:00Z"),
    isActive: true,
    type: "binary",
    completions: [
      { date: "2024-07-19", value: 1, timestamp: createSampleTimestamp("2024-07-19T18:00:00Z") },
      { date: "2024-07-21", value: 1, timestamp: createSampleTimestamp("2024-07-21T17:30:00Z") },
    ],
    isBadHabit: false,
    icon: "dumbbell",
    iconColor: "blue",
    frequency: "3x-week", // Example of non-daily
    isAbsolute: false,
  },
  {
    userId: "user2@example.com",
    title: "Read Pages from Book",
    description: "Read at least 20 pages.",
    category: "Learning",
    createdAt: createSampleTimestamp("2024-06-10T21:00:00Z"),
    isActive: true,
    type: "quantitative",
    targetValue: 20,
    targetUnit: "pages",
    completions: [
      { date: "2024-07-20", value: 25, timestamp: createSampleTimestamp("2024-07-20T21:30:00Z") },
      { date: "2024-07-21", value: 15, timestamp: createSampleTimestamp("2024-07-21T22:00:00Z") }, // Did not meet target
    ],
    isBadHabit: false,
    icon: "book-open",
    iconColor: "teal",
    frequency: "daily",
    isAbsolute: true,
    streak: 5, // Example streak
  },
  {
    userId: "user1@example.com",
    title: "Drink Water",
    description: "Drink 100 ounces of water daily.",
    category: "Nutrition & Fueling",
    createdAt: createSampleTimestamp("2024-07-01T09:00:00Z"),
    isActive: true,
    type: "quantitative",
    targetValue: 100,
    targetUnit: "ounces",
    completions: [], // No completions yet
    isBadHabit: false,
    icon: "glass-water", // This was a custom icon, example
    iconColor: "sky",
    frequency: "daily",
    isAbsolute: true,
  }
];

// Note: For userId in sampleHabits, it is currently using email.
// In a real Firestore setup, this would be the actual Firebase Authentication UID.
// This is just for illustrative sample data.
// The habitId field is omitted from these samples as it would be auto-generated by Firestore upon creation.
// If these samples were representing data *retrieved* from Firestore, habitId would be present.
